#Different buffers: stored as a list [valve-id,cnc-plate,cnc-well or position ]
buffers:
    wash_SABER_v3: [3,null,null]
    wash_v4: [4,null,null]
    image_v5: [5,null,null]

    clean_plate: [6,1,A1]
    prime_plate: [6,1,A2]
    
    dapi_r1: [6,1,A3]
    w_r1: [6,1,A4]
    h_r1: [6,1,A5]

    w_r2: [6,1,A6]
    h_r2: [6,1,A7]

    w_r3: [6,1,A8]
    h_r3: [6,1,A9]
    
    w_r4: [6,1,A10]
    h_r4: [6,1,A11]

    w_r5: [6,1,A12]
    h_r5: [6,1,B1]
    SAB_w_r5: [6,1,B2]
    SAB_h_IM_r5: [6,1,B3]   

    w_r6: [6,1,B4]
    h_r6: [6,1,B5]
    SAB_w_r6: [6,1,B6]
    SAB_h_IM_r6: [6,1,B7]   

    w_r7: [6,1,B8]
    h_r7: [6,1,B9]
    SAB_w_r7: [6,1,B10]
    SAB_h_IM_r7: [6,1,B11]   

    w_r8: [6,1,B12]
    h_r8: [6,1,C1]
    SAB_w_r8: [6,1,C2]
    SAB_h_IM_r8: [6,1,C3]   


# Sequence of a given fluidic run. Possible actions and parameters are "buffer": buffers listed in buffer_config.yaml, ii will be looped over; pump: time for pumping [s], pause: time for pause [s], image: 1.
sequence:
    - buffer: w_ii
    - pump: 180
    - buffer: h_ii
    - pump: 180
    - pause: 1200
    - buffer: wash_v4
    - pump: 180
    - pause: 180
    - - round: r1
      - buffer: dapi_ii
      - pump: 180
      - pause: 180
      - buffer: wash_v4
      - pump: 180
      - pause: 60  
    - pump: 180
    - pause: 180
    - - round: r5,r6,r7,r8
      - buffer: SAB_w_ii
      - pump: 180
      - pause: 180
      - buffer: SAB_h_IM_ii  
      - pump: 180
      - pause: 1200
      - buffer: wash_SABER_v3
      - pump: 180
      - pause: 180
      - buffer: wash_SABER_v3
      - pump: 180
      - pause: 180
    - buffer: image_v5
    - pump: 180  
    - pause: 120      
    
#Well plate setup: once calibrated, you usuall don't have to change this
well_plate:
    top_right:
      x: 63
      y: 99
    bottom_left:
      x: 0
      y: 0
    columns: 8
    rows: 12
    well_spacing: 9
    z_base: -37
    feed: 500