microscope:
    type: 'NIKON_TI'
    xy_drive_name: 'TIXYDrive'
    z_drive_name: 'TIPFSOffset'
    channel_group: 'channels'
    channels: ['Cy3_75', 'Cy5_45']
    channel_blank: DAPI_0
    channel_exposures_ms: [300,200]
    z_start: -10 
    z_end: 10
    z_step: 2.5
    mm_app_path: 'C:\Program Files\Micro-Manager-nightly'
    mm_config_file: 'Z_PFS.cfg'
