#Different buffers: stored as a list [valve-id,cnc-plate,cnc-well or position ]
buffers:
    wash_valve4: [4,null,null]
    image_valve5: [5,null,null]
    clean_plate: [6,1,A1]
    prime_plate: [6,1,A2]
    dapi_r1: [6,1,A3]
    w_r1: [6,1,A4]
    h_r1: [6,1,A5]
    w_r2: [6,1,A6]
    h_r2: [6,1,A7]
    w_r3: [6,1,A8]
    h_r3: [6,1,A9]
    w_r4: [6,1,A10]
    h_r4: [6,1,A11]
   

# Sequence of a given fluidic run. Possible actions and parameters are "buffer": buffers listed in buffer_config.yaml, ii will be looped over; pump: time for pumping [s], pause: time for pause [s], image: 1.
sequence:
#    - wait:
    - buffer: w_ii
    - pump: 180
    - buffer: h_ii
    - pump: 180
    - pause: 1200
    - buffer: wash_valve4
    - pump: 180
    - pause: 180
    - - round: r1
      - buffer: dapi_ii
      - pump: 180 
    - buffer: image_valve5
    - pump: 180     
    
#Well plate setup: once calibrated, you usuall don't have to change this
well_plate:
    top_right:
      x: 63
      y: 99
    bottom_left:
      x: 0
      y: 0
    columns: 8
    rows: 12
    well_spacing: 9
    z_base: -39
    feed: 500


    

    
